DROP DATABASE IF EXISTS TRUONGHOC; 
CREATE DATABASE TRUONGHOC;
USE TRUONGHOC;

DROP TABLE IF EXISTS DM_PHG_GDDT;
CREATE TABLE DM_PHG_GDDT(
    Ma CHAR(6) NOT NULL,
    /*
    XXX - NULL
    Q01 Q02 Q03 Q04 Q05 Q06 Q07 Q08 Q09 Q10 Q11 Q12
    BTN BTH TBI BCH GVP PNH CGI CCH HMN NHB TPH TDC 
    */
    TenPhg VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY(Ma)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS DM_LH;
CREATE TABLE DM_LH(
    MaLH CHAR(6) NOT NULL,
    /*
    XX - NULL
    CL
    DL
    TT
    */
    TenLH VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY(MaLH)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS DM_LT;
CREATE TABLE DM_LT(
    MaLT CHAR(6) NOT NULL, 
    /*
    XXXXXX - NULL
    TTGDTX
    TTGDNN
    GDNNTX
    PTHONG
    DANTOC
    NKTDTT
    CHUYEN
    */
    TenLT VARCHAR(50) NOT NULL,
    PRIMARY KEY(MaLT)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS MN;
CREATE TABLE MN(
    MaTrg VARCHAR(20) NOT NULL,
    TenTrg VARCHAR(100) NOT NULL,
    DC VARCHAR(255) DEFAULT NULL,
    MaPhgGDDT CHAR(6) NOT NULL,
    MaLH CHAR(6) NOT NULL,
    MaLT CHAR(6) NOT NULL,

    PRIMARY KEY(MaTrg),
    CONSTRAINT FOREIGN KEY(MaLH) REFERENCES DM_LH(MaLH),
    CONSTRAINT FOREIGN KEY(MaLT) REFERENCES DM_LT(MaLT),
    CONSTRAINT FOREIGN KEY(MaPhgGDDT) REFERENCES DM_PHG_GDDT(Ma)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS TH;
CREATE TABLE TH(
    MaTrg VARCHAR(20) NOT NULL,
    TenTrg VARCHAR(100) NOT NULL,
    DC VARCHAR(255) DEFAULT NULL,
    MaPhgGDDT CHAR(6) NOT NULL,
    MaLH CHAR(6) NOT NULL,
    MaLT CHAR(6) NOT NULL,

    PRIMARY KEY(MaTrg),
    CONSTRAINT FOREIGN KEY(MaLH) REFERENCES DM_LH(MaLH),
    CONSTRAINT FOREIGN KEY(MaLT) REFERENCES DM_LT(MaLT),
    CONSTRAINT FOREIGN KEY(MaPhgGDDT) REFERENCES DM_PHG_GDDT(Ma)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS THCS;
CREATE TABLE THCS(
    MaTrg VARCHAR(20) NOT NULL,
    TenTrg VARCHAR(100) NOT NULL,
    DC VARCHAR(255) DEFAULT NULL,
    MaPhgGDDT CHAR(6) NOT NULL,
    MaLH CHAR(6) NOT NULL,
    MaLT CHAR(6) NOT NULL,

    PRIMARY KEY(MaTrg),
    CONSTRAINT FOREIGN KEY(MaLH) REFERENCES DM_LH(MaLH),
    CONSTRAINT FOREIGN KEY(MaLT) REFERENCES DM_LT(MaLT),
    CONSTRAINT FOREIGN KEY(MaPhgGDDT) REFERENCES DM_PHG_GDDT(Ma)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS THPT;
CREATE TABLE THPT(
    MaTrg VARCHAR(20) NOT NULL,
    TenTrg VARCHAR(100) NOT NULL,
    DC VARCHAR(255) DEFAULT NULL,
    MaPhgGDDT CHAR(6) NOT NULL,
    MaLH CHAR(6) NOT NULL,
    MaLT CHAR(6) NOT NULL,

    PRIMARY KEY(MaTrg),
    CONSTRAINT FOREIGN KEY(MaLH) REFERENCES DM_LH(MaLH),
    CONSTRAINT FOREIGN KEY(MaLT) REFERENCES DM_LT(MaLT),
    CONSTRAINT FOREIGN KEY(MaPhgGDDT) REFERENCES DM_PHG_GDDT(Ma)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS GDTX;
CREATE TABLE GDTX(
    MaTrg VARCHAR(20) NOT NULL,
    TenTrg VARCHAR(100) NOT NULL,
    DC VARCHAR(255) DEFAULT NULL,
    MaPhgGDDT CHAR(6) NOT NULL,
    MaLH CHAR(6) NOT NULL,
    MaLT CHAR(6) NOT NULL,

    PRIMARY KEY(MaTrg),
    CONSTRAINT FOREIGN KEY(MaLH) REFERENCES DM_LH(MaLH),
    CONSTRAINT FOREIGN KEY(MaLT) REFERENCES DM_LT(MaLT),
    CONSTRAINT FOREIGN KEY(MaPhgGDDT) REFERENCES DM_PHG_GDDT(Ma)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
